# ---------------------------------------------------------------------------
# Tests generated by Claude
# ---------------------------------------------------------------------------

import polars as pl
import pytest

from src.python_janitor.dataframes import (
    _col_apply_case,
    _col_normalize_whitespace,
    _col_remove_special_characters,
    clean_dataframe,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def make_df(*cols: str) -> pl.DataFrame:
    """Create a single-row DataFrame with the given column names."""
    return pl.DataFrame({col: [None] for col in cols})


def col_names(df: pl.DataFrame) -> list[str]:
    return df.columns


# ---------------------------------------------------------------------------
# _col_normalize_whitespace
# ---------------------------------------------------------------------------
class TestColNormalizeWhitespace:
    def test_strips_leading_trailing(self):
        df = make_df("  hello  ", "  world  ")
        assert col_names(_col_normalize_whitespace(df)) == ["hello", "world"]

    def test_collapses_internal_spaces(self):
        df = make_df("hello   world")
        assert col_names(_col_normalize_whitespace(df)) == ["hello world"]

    def test_collapses_tabs_and_newlines(self):
        df = make_df("hello\t\nworld")
        assert col_names(_col_normalize_whitespace(df)) == ["hello world"]

    def test_already_clean(self):
        df = make_df("hello", "world")
        assert col_names(_col_normalize_whitespace(df)) == ["hello", "world"]

    def test_empty_column_name(self):
        df = make_df("   ")
        assert col_names(_col_normalize_whitespace(df)) == [""]

    def test_does_not_modify_data(self):
        df = make_df("  hello  ")
        assert _col_normalize_whitespace(df).shape == df.shape


# ---------------------------------------------------------------------------
# _col_apply_case
# ---------------------------------------------------------------------------
class TestColApplyCase:
    def test_default_is_snake_case(self):
        df = make_df("Hello World", "FooBar")
        assert col_names(_col_apply_case(df)) == ["hello_world", "foo_bar"]

    def test_snake_case(self):
        df = make_df("Hello World", "FooBar")
        assert col_names(_col_apply_case(df, case="snake")) == ["hello_world", "foo_bar"]

    def test_kebab_case(self):
        df = make_df("Hello World", "FooBar")
        assert col_names(_col_apply_case(df, case="kebab")) == ["hello-world", "foo-bar"]

    def test_camel_case(self):
        df = make_df("Hello World", "foo_bar")
        assert col_names(_col_apply_case(df, case="camel")) == ["helloWorld", "fooBar"]

    def test_pascal_case(self):
        df = make_df("hello world", "foo_bar")
        assert col_names(_col_apply_case(df, case="pascal")) == ["HelloWorld", "FooBar"]

    def test_invalid_case_raises(self):
        df = make_df("hello")
        with pytest.raises(ValueError):
            _col_apply_case(df, case="invalid")  # type: ignore[arg-type]

    def test_does_not_modify_data(self):
        df = make_df("Hello World")
        assert _col_apply_case(df).shape == df.shape


# ---------------------------------------------------------------------------
# _col_remove_special_characters
# ---------------------------------------------------------------------------
class TestColRemoveSpecialCharacters:
    def test_removes_punctuation(self):
        df = make_df("hello, world!", "foo@bar")
        assert col_names(_col_remove_special_characters(df)) == ["hello world", "foobar"]

    def test_strips_accents(self):
        df = make_df("café")
        assert col_names(_col_remove_special_characters(df)) == ["cafe"]

    def test_normalizes_umlaut(self):
        df = make_df("wörld")
        assert col_names(_col_remove_special_characters(df)) == ["woerld"]

    def test_combined_special_and_unicode(self):
        df = make_df("héllo, wörld!")
        assert col_names(_col_remove_special_characters(df)) == ["hello woerld"]

    def test_already_clean(self):
        df = make_df("hello", "world")
        assert col_names(_col_remove_special_characters(df)) == ["hello", "world"]

    def test_does_not_modify_data(self):
        df = make_df("héllo!")
        assert _col_remove_special_characters(df).shape == df.shape


# ---------------------------------------------------------------------------
# clean_dataframe
# ---------------------------------------------------------------------------
class TestCleanDataframe:
    def test_defaults(self):
        df = make_df("  Hello World  ", "fooBar")
        assert col_names(clean_dataframe(df)) == ["hello_world", "foo_bar"]

    def test_case_kebab(self):
        df = make_df("Hello World")
        assert col_names(clean_dataframe(df, case="kebab")) == ["hello-world"]

    def test_case_camel(self):
        df = make_df("Hello World")
        assert col_names(clean_dataframe(df, case="camel")) == ["helloWorld"]

    def test_case_pascal(self):
        df = make_df("hello world")
        assert col_names(clean_dataframe(df, case="pascal")) == ["HelloWorld"]

    def test_ascii_only_true(self):
        df = make_df("café_column")
        assert col_names(clean_dataframe(df, ascii_only=True)) == ["cafe_column"]

    def test_ascii_only_false(self):
        df = make_df("café_column")
        assert col_names(clean_dataframe(df, ascii_only=False)) == ["café_column"]

    def test_full_pipeline(self):
        df = make_df("  Héllo,   Wörld!  ")
        assert col_names(clean_dataframe(df, case="snake", ascii_only=True)) == ["hello_woerld"]

    def test_invalid_case_raises(self):
        df = make_df("hello")
        with pytest.raises(ValueError):
            clean_dataframe(df, case="invalid")  # type: ignore[arg-type]

    def test_does_not_modify_data(self):
        df = make_df("Hello World")
        assert clean_dataframe(df).shape == df.shape

    def test_empty_dataframe(self):
        df = pl.DataFrame()
        assert clean_dataframe(df).columns == []
